name: Build & Deploy to Azure App Service (docker option)

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: btTestingContainers
  DOCKER_IMAGE_TAG: "btron/echobot:latest"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to registry
        uses: docker/login-action@v2
        with:
          registry: https://index.docker.io/v1/
          username: ${{ secrets.AzureAppService_ContainerUsername_9f8bd83002564f19a3bed16bc0aa96d5 }}
          password: ${{ secrets.AzureAppService_ContainerPassword_b550b84c55884cf5b61f0a28bc7d51e0 }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_IMAGE_TAG }}
          file: EchoBot/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: production
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: production
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_5ba181518b994b9d9426065e6ad525fe }}
          images: ${{ env.DOCKER_IMAGE_TAG }}
