name: Trigger auto deployment for bot-app-container

on:
  push:
    branches: [main]
    paths:
      - "EchoBot/**"
      - ".github/workflows/bot-app-container-AutoDeployTrigger-8c3cc2b7-5c22-4155-92c4-d4ffba790288.yml"

  # Allow mannually trigger
  workflow_dispatch:

env:
  DOCKER_IMAGE_TAG: "btron/echobot:latest"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: https://index.docker.io/v1/
          username: ${{ secrets.BOTAPPCONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.BOTAPPCONTAINER_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_IMAGE_TAG }}
          file: EchoBot/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.BOTAPPCONTAINER_AZURE_CREDENTIALS }}

      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n bot-app-container -g rg-testing-purpose --server hub.docker.com --username  ${{ secrets.BOTAPPCONTAINER_REGISTRY_USERNAME }} --password ${{ secrets.BOTAPPCONTAINER_REGISTRY_PASSWORD }}
            az containerapp update -n bot-app-container -g rg-testing-purpose --image hub.docker.com/btron/echobot:${{ github.sha }}
